import cv2
import numpy as np
import onnxruntime as ort
from PIL import Image

from src.config import config

class U2Net:
    """
    U2-Net model (https://arxiv.org/pdf/2005.09007) inference for identifying exposed skin regions within the detected face.

    Attributes:
        session (onnxruntime.InferenceSession): ONNX runtime session for U2-Net model inference.
        input_name (str): Name of the input image.
        input_shape (tuple): Shape of the input image.
    """
    def __init__(self, model_path):    
        provider = ["CUDAExecutionProvider"] if config.DEVICE == 'cuda' else ["CPUExecutionProvider"]
        sess_options = ort.SessionOptions()
        sess_options.log_severity_level = 3                                                 # to supress warnings       
        self.session = ort.InferenceSession(model_path, sess_options=sess_options, providers=provider)
        
        self.input_name = self.session.get_inputs()[0].name
        self.input_shape = self.session.get_inputs()[0].shape[2], self.session.get_inputs()[0].shape[3]

    def process_img(self, img):
        """ Process the input image based on U2-Net requirements.

        Args:
            img (PIL.Image): Input image to be passed through U2-Net.

        Returns:
            processed_img (dict): Processed input image in the dict form required by ONNX runtime.
        """
        img = img.convert("RGB").resize(size=self.input_shape, resample=Image.LANCZOS)      # convert to RGB and resize to (512, 512, 3)
        img_array = np.array(img).astype(np.float32) / 255.0                                # convert to array and min-max norm.
        img_array = img_array.transpose(2, 0, 1)[np.newaxis, :]                             # reshape to (1, 3, 512, 512)
        processed_img = {self.input_name: img_array}
        return processed_img

    def predict(self, img):
        """ Pass the input image through U2-Net to perform skin segmentation.

        Args:
            img (np.ndarray): Input image to be passed through U2-Net.

        Returns:
            segmented_img (np.ndarray): Output image with non-skin regions masked out with black pixels.
        """
        # process image and pass through U2-Net
        img = Image.fromarray(img)                                                          # convert to PIL, shape: (H, W, 3)
        img = img.transpose(Image.FLIP_LEFT_RIGHT) if hasattr(img, 'transpose') else img    # flip horizontally if needed
        input_img = self.process_img(img)                                                   # dict where value is of shape: (1, 3, 512, 512)
        mask = self.session.run(None, input_img)[0].squeeze()                               # pixel values in [0, 1], shape: (7, 1, 1, 512, 512) -> (512, 512)

        # process segmentation mask generated by U2-Net
        mask = (mask * 255).astype(np.uint8)                                                # scale to get pixel values in [0, 255], shape: (512, 512)
        mask = cv2.resize(mask, (img.width, img.height), interpolation=cv2.INTER_LANCZOS4)  # resize to input image shape (note: cv2 uses (W, H) format for resizing), shape: (H, W)
        mask_3d = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)                                    # greyscale to RGB by replicating across 3 channels, shape: (H, W, 3)

        # apply skin mask to input image, essentially apply composite with black background
        segmented_img = (np.array(img) * (mask_3d / 255.0)).astype(np.uint8)
        
        return segmented_img